runtime: python27
api_version: 1
threadsafe: true

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : '1'

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /cron/.*
  script: handlers.app
  login: admin

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: handlers.app

libraries:
- name: ssl
  version: latest

- name: webapp2
  version: latest

skip_files:
  # Default
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  # Custom
  - ^venv$
