application: uark-notifier
version: 0-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cron/.*
  script: handlers.app
  login: admin

- url: /.*
  script: handlers.app

libraries:
- name: ssl
  version: latest

- name: webapp2
  version: latest
